resolver: nightly-2022-06-11
packages:
- .

extra-deps:
- MissingH-1.5.0.0
- OddWord-1.0.2.0
- OneTuple-0.3.1
- Unique-0.4.7.9
- aeson-2.0.3.0
- async-timer-0.2.0.0
- barbies-2.0.3.1
- beam-core-0.9.2.1
- beam-migrate-0.5.1.2
- beam-sqlite-0.5.1.2
- blaze-textual-0.2.2.1
- blockfrost-api-0.3.1.0
- blockfrost-client-core-0.2.0.0
- blockfrost-client-0.3.1.0
- canonical-json-0.6.0.0
- command-0.1.1
- composition-prelude-3.0.0.2
- cryptostore-0.2.1.0
- dependent-map-0.4.0.0
- dependent-sum-0.7.1.0
- dependent-sum-template-0.1.1.1
- dhall-1.41.1
- dhall-json-1.7.10
- docopt-0.7.0.7
- dom-lt-0.2.3
- ekg-0.4.0.15
- ekg-core-0.1.1.7
- extra-1.7.10
- freer-simple-1.2.1.2
- generic-lens-2.2.1.0
- generic-lens-core-2.2.1.0
- gray-code-0.3.1
- hedgehog-1.1.1
- hspec-2.9.4
- hspec-core-2.9.4
- io-streams-haproxy-1.0.1.0
- int-cast-0.2.0.0
- jwt-0.11.0
- lazy-search-0.1.2.1
- libsystemd-journal-1.4.5
- monoidal-containers-0.6.2.0
- moo-1.2
- network-3.1.2.7
- newtype-0.2.2.0
- nothunks-0.1.3
- openapi3-3.2.1
- partial-order-0.2.0.0
- pqueue-1.4.1.4
- protolude-0.3.1
- recursion-schemes-5.2.2.2
- row-types-1.0.1.2
- semialign-1.2.0.1
- servant-multipart-client-0.12.1
- servant-options-0.1.0.0
- servant-subscriber-0.7.0.0
- servant-websockets-2.0.0
- size-based-0.1.2.0
- sqlite-simple-0.4.18.0
- snap-core-1.0.4.2
- snap-server-1.1.2.0
- statistics-linreg-0.3
- streaming-binary-0.3.0.1
- th-extras-0.0.0.6
- time-interval-0.1.1
- time-out-0.2
- transformers-except-0.1.2

- git: https://github.com/haskell-works/hw-aeson
  commit: d99d2f3e39a287607418ae605b132a3deb2b753f
  # nix-sha256: sha256-xO4/zPMBmZtBXFwHF8p3nw4TilrJHxH54mfg9CRnuO8=
- git: https://github.com/vshabanov/ekg-json
  commit: 00ebe7211c981686e65730b7144fbf5350462608
  # nix-sha256: sha256-VT8Ur585TCn03P2TVi6t92v2Z6tl8vKijICjse6ocv8=
- git: https://github.com/input-output-hk/ekg-forward
  commit: 297cd9db5074339a2fb2e5ae7d0780debb670c63
- git: https://github.com/Quid2/flat.git
  commit: 559617e058098b776b431e2a67346ad3adea2440
- git: https://github.com/input-output-hk/purescript-bridge.git
  commit: 47a1f11825a0f9445e0f98792f79172efef66c00
- git: https://github.com/input-output-hk/servant-purescript.git
  commit: 44e7cacf109f84984cd99cd3faf185d161826963
- git: https://github.com/input-output-hk/cardano-crypto.git
  commit: f73079303f663e028288f9f4a9e08bcca39a923e
  # nix-sha256: sha256-2Fipex/WjIRMrvx6F3hjJoAeMtFd2wGnZECT0kuIB9k=
- git: https://github.com/input-output-hk/cardano-base
  commit: 0f3a867493059e650cda69e20a5cbf1ace289a57
  subdirs:
    - base-deriving-via
    - binary
    - binary/test
    - cardano-crypto-class
    - cardano-crypto-praos
    - cardano-crypto-tests
    - measures
    - orphans-deriving-via
    - slotting
    - strict-containers
- git: https://github.com/mlabs-haskell/cardano-prelude
  commit: 713c7ae79a4d538fcd653c976a652913df1567b9
  subdirs:
    - cardano-prelude
    - cardano-prelude-test
- git: https://github.com/input-output-hk/cardano-addresses
  commit: 56746f558d57a6b1d66d20eaac8a83dc4455cb4f
  subdirs:
    - command-line
    - core
  # nix-sha256: sha256-zo+XJJsIiSkUlcxuPhRQRCxcWYOkDXnAApBF9Pj5Tls=
- git: https://github.com/locallycompact/cardano-wallet
  commit: e19b8a862d9c7f89df4931f9c85ba2314c437678
  subdirs:
    - lib/cli
    - lib/core
    - lib/core-integration
    - lib/dbvar
    - lib/launcher
    - lib/numeric
    - lib/shelley
    - lib/strict-non-empty-containers
    - lib/test-utils
    - lib/text-class
  # nix-sha256: sha256-LvxBU9OJ/IdpO4ZT79aVzP2jxWqLKOipA3zdV6fyxaM=
- git: https://github.com/input-output-hk/ouroboros-network
  commit: ad47441e9e399495579d7dd05ccaf96b46a487b2
  subdirs:
    - io-classes
    - io-sim
    - monoidal-synchronisation
    - network-mux
    - ntp-client
    - ouroboros-network
    - ouroboros-network-testing
    - ouroboros-network-framework
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-protocol
    - ouroboros-consensus-shelley
    - strict-stm
    - typed-protocols
    - typed-protocols-cborg
    - typed-protocols-examples
- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: eb7854d1337637b8672af1227b276aa33a658f47
  subdirs:
    - iohk-monitoring
    - tracer-transformers
    - contra-tracer
    - plugins/backend-aggregation
    - plugins/backend-ekg
    - plugins/backend-monitoring
    - plugins/backend-trace-forwarder
    - plugins/scribe-systemd
  # nix-sha256: sha256-IxsBrFOfehIh/krI3Cr7xyEo8JRcU7OLM0nCCSkMiNI=
- git: https://github.com/input-output-hk/cardano-ledger-specs
  commit: 1db68a3ec0a2dcb5751004beb22b906162474f23
  subdirs:
    - eras/alonzo/impl
    - eras/babbage/impl
    - eras/byron/chain/executable-spec
    - eras/byron/crypto
    - eras/byron/crypto/test
    - eras/byron/ledger/executable-spec
    - eras/byron/ledger/impl
    - eras/byron/ledger/impl/test
    - eras/shelley/impl
    - eras/shelley/test-suite
    - eras/shelley-ma/impl
    - libs/cardano-data
    - libs/cardano-ledger-core
    - libs/cardano-ledger-pretty
    - libs/cardano-protocol-tpraos
    - libs/compact-map
    - libs/non-integral
    - libs/set-algebra
    - libs/small-steps
    - libs/small-steps-test
  # nix-sha256: sha256-KhB23QzYNLw6erBLzcgxnK3VF1LmtqZ4KyauqbcU+w4=
- git: https://github.com/input-output-hk/cardano-node.git
  commit: 65422ff373f2f88a563afa746a9a16d211ffdc7c
  subdirs:
    - cardano-api
    - cardano-cli
    - cardano-git-rev
    - cardano-node
    - cardano-submit-api
    - cardano-testnet
    - trace-dispatcher
    - trace-forward
    - trace-resources
  # nix-sha256: sha256-wkbrGgrwyfW4+KC50zKO+XmmcrgOEwBAUx5ZV61wfGc=
- git: https://github.com/input-output-hk/cardano-config
  commit: e9de7a2cf70796f6ff26eac9f9540184ded0e4e6
- git: https://github.com/input-output-hk/optparse-applicative
  commit: 7497a29cb998721a9068d5725d49461f2bba0e7a
  # nix-sha256: sha256-uQx+SEYsCH7JcG3xAT0eJck9yq3y0cvx49bvItLLer8=
- git: https://github.com/input-output-hk/Win32-network
  commit: 3825d3abf75f83f406c1f7161883c438dac7277d
- git: https://github.com/input-output-hk/goblins
  commit: cde90a2b27f79187ca8310b6549331e59595e7ba
- git: https://github.com/input-output-hk/plutus
  commit: 3c81f60746f50b596d3209c38e048ebb473c93b8
  subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - word-array
    - prettyprinter-configurable
    - stubs/plutus-ghc-stub
  # nix-sha256: sha256-SqZM0g/lPiJayXBAUkJweY8akmA/3M3vAVB+XHx/3WQ=

flags:
  cardano-prelude:
    development: true
  cardano-binary:
    development: true
  cardano-crypto-class:
    development: true
